### ISSUE TITLE
Receiving messages from users?

### ISSUE THREAD

**Issue by weekian** [crisboarna/fb-messenger-bot-api#28]
Hi, just wondering if the client here refers to the bot or the user interacting with the bot?

I don't see any instructions on handling messages received from the user.

Thank you!

**Comment by teomaragakis** [comment]
Bump, I'd like to know this as well!

**Comment by teomaragakis** [comment]
@weekian Okay so I think figured it out:

Listening for messengers requires a post request endpoint, and from what I see there is no route that receives post requests. So the answer is no, There's no handler for receiving messages.

**Comment by crisboarna** [comment]
Hi,
Sorry for the late reply on this issue.

The client refers to the bot that is receiving the messages from the user.

Although there is no specific handler created for the messages as there is for validation, it can easily be created manually as per the example below. I am doing some work on it now to add Typescript support and will add an inbuilt message handling option as well.
`routes.js`
```
...
const router = require('express').Router();
const facebook = require('fb-messenger-bot-api').ValidateWebhook;
const postBackController = require('./postbackController');

router.get('/api/webhook', facebook.validate);
router.post('/api/webhook', postBackController);

```

`postbackController.js`
```
const client = new facebook.Client(process.env.PAGE_ACCESS_TOKEN);
const postBackController = function postBackController (req, res) {
let event = req.body.object.entry[0].messaging[0];
let senderId = event.sender.id;
let userMessage = event.message.text;
client.sentTextMessage(senderId, `You said: '${userMessage}'`);
}
```

This would be the barebones example of echoing user message. I will add class to handle extraction of this nicely this week or next latest ;)

**Comment by teomaragakis** [comment]
@crisboarna, I'd suggest adding this to the current version before upgrading to TS, but that's just me. Thanks for the great job, I'm learning a lot from your code.

**Comment by crisboarna** [comment]
@teomaragakis, the code already exists and am using it in another repo, just need to port it over, adding it before TS would result in having to do two refactors instead of one. 

Glad to hear it's educational ^^, hopefully on how to write code and not on how to not write it :P

**Comment by teomaragakis** [comment]
@crisboarna, looks great but my TS game is weak so I'll just take your word for it :)

Can't wait to see the postback functionality!

**Comment by crisboarna** [comment]
Took far longer than expected due to lack of time but I am releasing today the postback extraction and parsing logic in a shape & form. Open to suggestions for new features !

**Comment by teomaragakis** [comment]
Did you forget to push? :)

**Comment by crisboarna** [comment]
It has been pushed, just a little later than I was hoping for (27 Sept), but it got there :)
