### ISSUE TITLE
Great library - Can we add a method or configuration based auto validation of webhook messages

### ISSUE THREAD

**Issue by rasikas** [crisboarna/fb-messenger-bot-api#43]
First of thank you for a well written complete library (especially using TS)
I wish you could continuously maintain it. Is there a way you to include the message origin validation that FB has mentioned at the bottom of this page?

https://developers.facebook.com/docs/messenger-platform/webhook
Validating Webhook Events

Thanks

**Comment by crisboarna** [comment]
Hey, could you please expand on this a bit ? Where would you like this to be located ? As a utility method that checks incoming payload ? Or in the `FacebookMessageParser` class when it is extract each individual message to only return valid ones ?

**Comment by rasikas** [comment]
I think it should be a utility method that is accessible anywhere by passing the payload and any other required parameters. for ex: in my case, I use your library to prepare reply messages to messenger, I don't use (yet) your library to capture any incoming messages (webhook), so it is better to have the flexibility to use the validation method as a separate utility class, so we could use it whenever we need it. Hope that makes sense. Thank you

**Comment by mohyt** [comment]
@crisboarna : I am planning to create a PR for this as it's will be good to have a validation before parsing the messages.

**Comment by crisboarna** [comment]
Hey @rasikas , with the help of @mohyt your feature request has been merged and version 4.1.0 has message integrity validation added.

**Comment by rasikas** [comment]
@crisboarna , @mohyt thanks a lot !!!! this is valuable
