### ISSUE TITLE
`proxyData` parameter is not optional  in`Client` constructor 

### ISSUE THREAD

**Issue by rasikas** [crisboarna/fb-messenger-bot-api#44]
According to your example, `Client` should be constructed without `proxyData`
~~~ts
import {Client} from 'fb-messenger-bot-api';
const client = new Client(process.env.PAGE_ACCESS_TOKEN);
~~~
However `proxyData` is not marked as optional so we always have to pass `undefined` as the second param.
(when using the library in a typescript project)
https://github.com/crisboarna/fb-messenger-bot-api/blob/master/src/client/Client.ts#L39
~~~ts
  public constructor(token: string, proxyData: ProxyData) {
    this.requestData = { token };
    this.requestData = Utils.getProxyData(this.requestData, proxyData);
  }
~~~

**Comment by crisboarna** [comment]
Hey, thank you for pointing it out. I will finish the release today and will publish a new version solving all present issues + suggestions + more.

**Comment by crisboarna** [comment]
Made proxyData optional in latest version.
