### ISSUE TITLE
Template (and builder) classes are not exported

### ISSUE THREAD

**Issue by Inkdpixels** [crisboarna/fb-messenger-bot-api#47]
The docs mentions that this package comes with a bunch of Template and its builder classes (`Button, Generic, List, Media, OpenGraph, Receipt, Airline Boarding Pass, Airline Check In, Airline Flight Update, Airline Itinerary`) but they are not exported in the [`src/builders/index.ts`](https://github.com/crisboarna/fb-messenger-bot-api/blob/master/src/builders/index.ts) file.

Is this intended?

**Comment by crisboarna** [comment]
Hey, thank you for pointing it out as well. No it is not intended, fortunately it was an intermediary step towards the final endpoint release I wanted to get to. I will finish the release today and will publish a new version solving all present issues + suggestions + more.

**Comment by crisboarna** [comment]
Classes exported in latest version.
